<a href="https://colab.research.google.com/github/damaleshaunak4/collab-ann/blob/main/lists.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

LIST

In [4]:
my_list = [1,2,3,4,5,6,7]
my_list

[1, 2, 3, 4, 5, 6, 7]

NUMPY ARRAY

In [16]:
np1 = np.random.rand(4,4)
np1

array([[0.92404713, 0.5868733 , 0.27711316, 0.66798438],
       [0.59785185, 0.9637623 , 0.03120026, 0.47789756],
       [0.22783228, 0.39726297, 0.4022298 , 0.4248153 ],
       [0.69731478, 0.30773175, 0.65514343, 0.3058967 ]])

In [18]:
np1.dtype

dtype('float64')

TENSOR

In [20]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.8593, -0.1809, -0.3104,  1.0232],
        [ 0.9853, -0.7901, -0.3083,  0.4484],
        [-0.2164, -0.0070, -2.6435,  0.6500]])

In [25]:
tensor_3d = torch.ones(2,3,4)
tensor_3d

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [29]:
# Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor


tensor([[0.9240, 0.5869, 0.2771, 0.6680],
        [0.5979, 0.9638, 0.0312, 0.4779],
        [0.2278, 0.3973, 0.4022, 0.4248],
        [0.6973, 0.3077, 0.6551, 0.3059]], dtype=torch.float64)