<a href="https://colab.research.google.com/github/damaleshaunak4/collab-ann/blob/main/math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [5]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [6]:
# addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [7]:
# subtract
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [9]:
# sub Function
torch.sub(tensor_a, tensor_b)

tensor([-4, -4, -4, -4])

In [10]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [11]:
# Mul Longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [12]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [13]:
# Division longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [14]:
# Remender Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [15]:
# remender longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [16]:
#Exponents / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [24]:
#another way to write Longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [25]:
#reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [26]:
tensor_a

tensor([1, 2, 3, 4])

In [27]:
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [28]:
tensor_a

tensor([ 6,  8, 10, 12])